<html>
<head>
<title>PHP目录树演示</title>
<style>
  BODY { font-family : Verdana,Arial; }
  TD   { font-family : Verdana,Arial; font-size : 8pt; }
  A    { text-decoration : none; background-color : #EEFFEE; }
</style>
</head>
<body bgcolor=#eeffee link=#339933>
<h4>PHP目录树演示</h4>
<?php  
  /*********************************************/
  /*  PHP目录树演示                      */
  /*********************************************/

  /*********************************************/
  /*  文件结构            */
  /*********************************************/
  
  $treefile = "demomenu.txt";
  
  /*********************************************/
  /*  包函树节点                        */
  /*********************************************/
  
  require "treemenu.inc";
  
?>

</body>
</html>